### ISSUE TITLE
enable joint control of playable character: by human and by script

### ISSUE THREAD

**Issue by noskill** [trueagi-io/minecraft-demo#120]

**Comment by CICS-Oleg** [comment]
What do you mean by joint control? @noskill

**Comment by Necr0x0Der** [comment]
Currently, either the player or the bot controls the character (this is switched by pressing Enter). It would be convenient in some cases either for the player or the bot to interfere with another controller's actions without switching control mode (e.g., the player just presses 'a' single time to help the bot to get out of stuck, or the bot can automate small actions like choosing the best tool or hitting the block while the player is still controlling all other movement commands)

**Comment by noskill** [comment]
All logic is in KeyHook class. It's has a variable isOverridingPressess which
determines whether to override human input.

пн, 27 февр. 2023 г. в 13:38, Alexey Potapov ***@***.***>:

**Comment by noskill** [comment]
I was wrong, there are more motion related code

**Comment by Necr0x0Der** [comment]
Done on the Vereya side.
