### ISSUE TITLE
opening of inventory stop achiever

### ISSUE THREAD

**Issue by noskill** [trueagi-io/minecraft-demo#164]

**Comment by DaddyWesker** [comment]
It seems, problem not only in opening inventory but in changes to current active screen. I've tried also to open chat and met the same problem. Moreover, problem seems to be with attacking. I mean when agent is moving, opening chat or inventory or advancements seems to not interfere with agent taking commands. But when agent tries to attack some block, opening either of those things interrupts agent and it won't attack anymore and just stands.

**Comment by DaddyWesker** [comment]
Resolved.
