### ISSUE TITLE
test_vereya.py fails in setLoggingComponent 

### ISSUE THREAD

**Issue by CICS-Oleg** [trueagi-io/minecraft-demo#75]
VereyaPython.setLoggingComponent(VereyaPython.LoggingComponent.LOG_TCP, True)
Boost.Python.ArgumentError: Python argument types in
    VereyaPython.setLoggingComponent(LoggingComponent, bool)
did not match C++ signature:
    setLoggingComponent(malmo::Logger::LoggingComponent, bool)

**Comment by noskill** [comment]
i can't reproduce

**Comment by noskill** [comment]
c++ code is outdated by python version of Vereya
